create table if not exists public.form_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  type text not null check (type in ('inquiry', 'document-request')),
  name text not null,
  company text not null,
  country text,
  email text not null,
  whatsapp text,
  business_type text,
  division text,
  cooperation_type text,
  message text,
  document text
);

alter table public.form_submissions enable row level security;

comment on table public.form_submissions is
  'Server-side submissions from the FORJEN website inquiry and document request forms.';

-- No public INSERT/SELECT policies are intentionally created. The website API
-- writes with a server-only secret key, while browser clients cannot access rows.
